import { Collection } from './types';

export const INITIAL_COLLECTIONS: Collection[] = [
  {
    id: 'col-001',
    name: 'Painted',
    slug: 'painted',
    shortDescription: 'Custom hand-painted artwork on premium organic cotton.',
    detailedDescription: 'Each piece in our Painted collection is individually hand-crafted by master artisans using eco-friendly permanent fabric paints. No two garments are identical.',
    productsCount: 248,
    status: 'Active',
    featured: true,
    showOnHomepage: true,
    homepagePriority: 1,
    displayOrder: 1,
    displayStyle: 'Banner',
    createdDate: '10 May 2026',
    publishDate: '2026-05-10',
    icon: 'Palette',
    coverImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=600&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=1200&q=80',
    themeColor: '#facc15',
    marketing: {
      buttonText: 'Explore Painted Art',
      buttonUrl: '/collections/painted',
      promoLabel: 'Best Seller',
    },
    seo: {
      metaTitle: 'Hand Painted Apparel & Streetwear | BatalaBandi',
      metaDescription: 'Shop exclusive hand-painted shirts, kurtas, and oversized tees.',
      keywords: 'hand painted clothes, painted shirts, artisan streetwear',
    },
    analytics: {
      salesCount: 1840,
      revenue: '₹24,80,000',
      views: 45200,
      conversionRate: '4.1%',
      monthlySales: [
        { month: 'Mar', amount: 320000 },
        { month: 'Apr', amount: 480000 },
        { month: 'May', amount: 620000 },
        { month: 'Jun', amount: 510000 },
        { month: 'Jul', amount: 550000 },
      ],
    },
    assignedProducts: [
      { id: 'p-201', name: 'Artisan Phoenix Hand Painted Kurta', productType: 'Kurta', theme: 'Nature', price: '₹2,490', stock: 14, status: 'Active', image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=400&q=80', salesCount: 420 },
      { id: 'p-202', name: 'Celestial Dragon Painted Oversized Tee', productType: 'Oversized T-Shirt', theme: 'Anime', price: '₹1,890', stock: 28, status: 'Active', image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=400&q=80', salesCount: 680 },
      { id: 'p-203', name: 'Abstract Canvas Hand Painted Shirt', productType: 'Shirt', theme: 'Quotes', price: '₹2,190', stock: 8, status: 'Active', image: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=400&q=80', salesCount: 310 },
    ],
  },
  {
    id: 'col-002',
    name: 'Thread',
    slug: 'thread',
    shortDescription: 'Kantha stitch & intricate threadwork embroidery.',
    detailedDescription: 'Rooted in heritage craft, the Thread collection features traditional Bengal Kantha embroidery, contrast stitch borders, and rich textured fabrics.',
    productsCount: 165,
    status: 'Active',
    featured: true,
    showOnHomepage: true,
    homepagePriority: 2,
    displayOrder: 2,
    displayStyle: 'Card',
    createdDate: '15 Jun 2026',
    publishDate: '2026-06-15',
    icon: 'Needle',
    coverImage: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=600&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=1200&q=80',
    themeColor: '#8b5cf6',
    marketing: {
      buttonText: 'Shop Kantha Threadwork',
      buttonUrl: '/collections/thread',
      promoLabel: 'Trending',
    },
    seo: {
      metaTitle: 'Kantha Stitch & Threadwork Collection | BatalaBandi',
      metaDescription: 'Discover embroidered threadwork shirts, dupattas, and jackets.',
      keywords: 'kantha stitch, threadwork embroidery, traditional craft',
    },
    analytics: {
      salesCount: 1210,
      revenue: '₹18,20,000',
      views: 32400,
      conversionRate: '3.7%',
      monthlySales: [
        { month: 'Mar', amount: 210000 },
        { month: 'Apr', amount: 310000 },
        { month: 'May', amount: 450000 },
        { month: 'Jun', amount: 420000 },
        { month: 'Jul', amount: 430000 },
      ],
    },
    assignedProducts: [
      { id: 'p-204', name: 'Zari Border Kantha Silk Dupatta', productType: 'Saree & Dupatta', theme: 'Sports', price: '₹1,590', stock: 45, status: 'Active', image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=400&q=80', salesCount: 510 },
      { id: 'p-205', name: 'Embroidered Contrast Thread Shirt', productType: 'Shirt', theme: 'Nature', price: '₹1,990', stock: 19, status: 'Active', image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=400&q=80', salesCount: 340 },
    ],
  },
  {
    id: 'col-003',
    name: 'Printed',
    slug: 'printed',
    shortDescription: 'High-density screen prints & hand-block geometric patterns.',
    detailedDescription: 'Bold graphic screen prints and traditional wooden block prints combined on 240 GSM combed cotton tees and heavy fleece hoodies.',
    productsCount: 310,
    status: 'Active',
    featured: true,
    showOnHomepage: true,
    homepagePriority: 3,
    displayOrder: 3,
    displayStyle: 'Card',
    createdDate: '01 Apr 2026',
    publishDate: '2026-04-01',
    icon: 'Printer',
    coverImage: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=600&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=1200&q=80',
    themeColor: '#3b82f6',
    marketing: {
      buttonText: 'View Graphic Prints',
      buttonUrl: '/collections/printed',
      promoLabel: 'Hot',
    },
    seo: {
      metaTitle: 'Graphic & Block Printed Apparel | BatalaBandi',
      metaDescription: 'Browse high density printed streetwear and block printed shirts.',
      keywords: 'printed tshirts, screen print, block print shirt',
    },
    analytics: {
      salesCount: 2940,
      revenue: '₹35,40,000',
      views: 68100,
      conversionRate: '4.3%',
      monthlySales: [
        { month: 'Mar', amount: 500000 },
        { month: 'Apr', amount: 680000 },
        { month: 'May', amount: 790000 },
        { month: 'Jun', amount: 720000 },
        { month: 'Jul', amount: 850000 },
      ],
    },
    assignedProducts: [
      { id: 'p-206', name: 'Cyber Wave Screen Printed Hoodie', productType: 'Hoodie', theme: 'Anime', price: '₹2,690', stock: 52, status: 'Active', image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=400&q=80', salesCount: 1200 },
    ],
  },
  {
    id: 'col-004',
    name: 'Limited Edition',
    slug: 'limited-edition',
    shortDescription: 'Numbered 1-of-100 artist collaboration streetwear drops.',
    detailedDescription: 'Exclusive capsule collections released in strictly numbered quantities. Each garment includes a signed certificate of authenticity tag.',
    productsCount: 42,
    status: 'Active',
    featured: true,
    showOnHomepage: true,
    homepagePriority: 4,
    displayOrder: 4,
    displayStyle: 'Full Width',
    createdDate: '20 Jul 2026',
    publishDate: '2026-07-20',
    icon: 'Sparkles',
    coverImage: 'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?auto=format&fit=crop&w=600&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80',
    themeColor: '#ec4899',
    marketing: {
      buttonText: 'Shop Rare Drops',
      buttonUrl: '/collections/limited-edition',
      promoLabel: 'Limited',
    },
    seo: {
      metaTitle: 'Limited Edition Artist Drops | BatalaBandi',
      metaDescription: 'Rare numbered streetwear and artist collaboration apparel.',
      keywords: 'limited edition streetwear, artist drop, 1 of 100 clothes',
    },
    analytics: {
      salesCount: 840,
      revenue: '₹16,80,000',
      views: 29800,
      conversionRate: '2.8%',
      monthlySales: [
        { month: 'Mar', amount: 150000 },
        { month: 'Apr', amount: 280000 },
        { month: 'May', amount: 410000 },
        { month: 'Jun', amount: 390000 },
        { month: 'Jul', amount: 450000 },
      ],
    },
    assignedProducts: [
      { id: 'p-207', name: 'Monolith 1-of-100 Heavy Denim Jacket', productType: 'Jacket', theme: 'Marvel', price: '₹4,990', stock: 4, status: 'Active', image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=400&q=80', salesCount: 96 },
    ],
  },
  {
    id: 'col-005',
    name: 'Hand Painted',
    slug: 'hand-painted',
    shortDescription: 'Masterpiece wearable art painted by local artisans.',
    detailedDescription: 'Specialized sub-line focusing purely on custom brushwork and indigo dye art.',
    productsCount: 88,
    status: 'Active',
    featured: false,
    showOnHomepage: false,
    homepagePriority: 5,
    displayOrder: 5,
    displayStyle: 'Card',
    createdDate: '10 Feb 2026',
    publishDate: '2026-02-10',
    icon: 'Brush',
    coverImage: 'https://images.unsplash.com/photo-1490578474895-699cd4e2cf59?auto=format&fit=crop&w=600&q=80',
    themeColor: '#10b981',
    marketing: {
      buttonText: 'Discover Hand Art',
      buttonUrl: '/collections/hand-painted',
      promoLabel: 'Handmade',
    },
    seo: {
      metaTitle: 'Masterpiece Hand Painted Apparel | BatalaBandi',
      metaDescription: 'Wearable art painted by skilled Indian craftsmen.',
      keywords: 'wearable art, hand painted clothing, artisan fashion',
    },
    analytics: {
      salesCount: 650,
      revenue: '₹9,75,000',
      views: 18200,
      conversionRate: '3.5%',
      monthlySales: [
        { month: 'Mar', amount: 110000 },
        { month: 'Apr', amount: 180000 },
        { month: 'May', amount: 240000 },
        { month: 'Jun', amount: 210000 },
        { month: 'Jul', amount: 235000 },
      ],
    },
    assignedProducts: [],
  },
];
