import { AttributeGroup } from './types';

export const INITIAL_ATTRIBUTES: AttributeGroup[] = [
  {
    id: 'attr-colors',
    name: 'Colors',
    slug: 'colors',
    description: 'Visual color swatches and variant shades',
    type: 'Color Picker',
    enableFilter: true,
    visibleOnProductPage: true,
    required: true,
    sortingMode: 'Manual',
    status: 'Active',
    icon: 'Palette',
    values: [
      { id: 'v-black', name: 'Black', slug: 'black', displayLabel: 'Midnight Black', colorHex: '#000000', sortOrder: 1, productsCount: 248, status: 'Active' },
      { id: 'v-white', name: 'White', slug: 'white', displayLabel: 'Off White', colorHex: '#ffffff', sortOrder: 2, productsCount: 195, status: 'Active' },
      { id: 'v-red', name: 'Red', slug: 'red', displayLabel: 'Crimson Red', colorHex: '#ef4444', sortOrder: 3, productsCount: 112, status: 'Active' },
      { id: 'v-blue', name: 'Blue', slug: 'blue', displayLabel: 'Royal Blue', colorHex: '#3b82f6', sortOrder: 4, productsCount: 98, status: 'Active' },
      { id: 'v-navy', name: 'Navy', slug: 'navy', displayLabel: 'Dark Navy', colorHex: '#1e3a8a', sortOrder: 5, productsCount: 84, status: 'Active' },
      { id: 'v-emerald', name: 'Emerald', slug: 'emerald', displayLabel: 'Botanical Green', colorHex: '#10b981', sortOrder: 6, productsCount: 62, status: 'Active' },
    ],
  },
  {
    id: 'attr-sizes',
    name: 'Sizes',
    slug: 'sizes',
    description: 'Standard sizing metrics for apparel',
    type: 'Text',
    enableFilter: true,
    visibleOnProductPage: true,
    required: true,
    sortingMode: 'Custom',
    status: 'Active',
    icon: 'Ruler',
    values: [
      { id: 'v-xs', name: 'XS', slug: 'xs', displayLabel: 'Extra Small (36")', sortOrder: 1, productsCount: 140, status: 'Active' },
      { id: 'v-s', name: 'S', slug: 's', displayLabel: 'Small (38")', sortOrder: 2, productsCount: 310, status: 'Active' },
      { id: 'v-m', name: 'M', slug: 'm', displayLabel: 'Medium (40")', sortOrder: 3, productsCount: 420, status: 'Active' },
      { id: 'v-l', name: 'L', slug: 'l', displayLabel: 'Large (42")', sortOrder: 4, productsCount: 450, status: 'Active' },
      { id: 'v-xl', name: 'XL', slug: 'xl', displayLabel: 'Extra Large (44")', sortOrder: 5, productsCount: 380, status: 'Active' },
      { id: 'v-xxl', name: 'XXL', slug: 'xxl', displayLabel: 'Double XL (46")', sortOrder: 6, productsCount: 220, status: 'Active' },
    ],
  },
  {
    id: 'attr-materials',
    name: 'Materials',
    slug: 'materials',
    description: 'Fabric compositions and weave textures',
    type: 'Text',
    enableFilter: true,
    visibleOnProductPage: true,
    required: false,
    sortingMode: 'Alphabetical',
    status: 'Active',
    icon: 'Layers',
    values: [
      { id: 'v-cotton-100', name: '100% Cotton', slug: '100-cotton', displayLabel: '100% Pure Combed Cotton (240 GSM)', sortOrder: 1, productsCount: 380, status: 'Active' },
      { id: 'v-cotton-blend', name: 'Cotton Blend', slug: 'cotton-blend', displayLabel: '80% Cotton / 20% Polyester', sortOrder: 2, productsCount: 140, status: 'Active' },
      { id: 'v-fleece', name: 'Fleece', slug: 'fleece', displayLabel: '330 GSM Heavy Brushed Fleece', sortOrder: 3, productsCount: 110, status: 'Active' },
      { id: 'v-french-terry', name: 'French Terry', slug: 'french-terry', displayLabel: '280 GSM Unbrushed French Terry', sortOrder: 4, productsCount: 75, status: 'Active' },
      { id: 'v-linen', name: 'Linen', slug: 'linen', displayLabel: 'Organic Slub Linen', sortOrder: 5, productsCount: 48, status: 'Active' },
    ],
  },
  {
    id: 'attr-fit-types',
    name: 'Fit Types',
    slug: 'fit-types',
    description: 'Garment silhouette and body cut',
    type: 'Text',
    enableFilter: true,
    visibleOnProductPage: true,
    required: true,
    sortingMode: 'Manual',
    status: 'Active',
    icon: 'Shirt',
    values: [
      { id: 'v-regular-fit', name: 'Regular Fit', slug: 'regular-fit', displayLabel: 'Classic Regular Fit', sortOrder: 1, productsCount: 290, status: 'Active' },
      { id: 'v-oversized', name: 'Oversized', slug: 'oversized', displayLabel: 'Drop Shoulder Oversized Fit', sortOrder: 2, productsCount: 380, status: 'Active' },
      { id: 'v-slim-fit', name: 'Slim Fit', slug: 'slim-fit', displayLabel: 'Tailored Slim Fit', sortOrder: 3, productsCount: 120, status: 'Active' },
      { id: 'v-relaxed-fit', name: 'Relaxed Fit', slug: 'relaxed-fit', displayLabel: 'Comfort Relaxed Cut', sortOrder: 4, productsCount: 95, status: 'Active' },
    ],
  },
  {
    id: 'attr-sleeve-types',
    name: 'Sleeve Types',
    slug: 'sleeve-types',
    description: 'Sleeve length and shoulder construction',
    type: 'Text',
    enableFilter: true,
    visibleOnProductPage: true,
    required: false,
    sortingMode: 'Manual',
    status: 'Active',
    icon: 'Scissors',
    values: [
      { id: 'v-half-sleeve', name: 'Half Sleeve', slug: 'half-sleeve', displayLabel: 'Standard Half Sleeve', sortOrder: 1, productsCount: 410, status: 'Active' },
      { id: 'v-full-sleeve', name: 'Full Sleeve', slug: 'full-sleeve', displayLabel: 'Full Length Sleeve', sortOrder: 2, productsCount: 240, status: 'Active' },
      { id: 'v-sleeveless', name: 'Sleeveless', slug: 'sleeveless', displayLabel: 'Sleeveless Tank Cut', sortOrder: 3, productsCount: 45, status: 'Active' },
      { id: 'v-drop-shoulder', name: 'Drop Shoulder', slug: 'drop-shoulder', displayLabel: 'Streetwear Drop Shoulder', sortOrder: 4, productsCount: 310, status: 'Active' },
    ],
  },
  {
    id: 'attr-neck-types',
    name: 'Neck Types',
    slug: 'neck-types',
    description: 'Neckline and collar styling',
    type: 'Text',
    enableFilter: true,
    visibleOnProductPage: true,
    required: false,
    sortingMode: 'Manual',
    status: 'Active',
    icon: 'Circle',
    values: [
      { id: 'v-round-neck', name: 'Round Neck', slug: 'round-neck', displayLabel: 'Classic Crew Round Neck', sortOrder: 1, productsCount: 510, status: 'Active' },
      { id: 'v-polo-neck', name: 'Polo Neck', slug: 'polo-neck', displayLabel: 'Ribbed Polo Collar', sortOrder: 2, productsCount: 130, status: 'Active' },
      { id: 'v-hooded', name: 'Hooded', slug: 'hooded', displayLabel: 'Drawstring Double Layer Hood', sortOrder: 3, productsCount: 185, status: 'Active' },
    ],
  },
];
