import { InventoryItem } from './types';

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-001',
    sku: 'BB-TSH-001-BLK-M',
    productTitle: 'Cyber Samurai Oversized Heavyweight Tee',
    productImage: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=400&q=80',
    category: 'Tops',
    color: 'Black',
    size: 'M',
    location: 'Main Warehouse (WH-01)',
    availableStock: 15,
    reservedStock: 2,
    lowStockThreshold: 5,
    unitCost: 580,
    status: 'In Stock',
    updatedAt: '03 Aug 2026',
    logs: [
      {
        id: 'log-001',
        changeAmount: 15,
        previousStock: 0,
        newStock: 15,
        reason: 'Initial Stock',
        note: 'Factory shipment batch #104',
        user: 'Admin',
        timestamp: '03 Aug 2026, 14:30',
      },
    ],
  },
  {
    id: 'inv-002',
    sku: 'BB-TSH-001-BLK-L',
    productTitle: 'Cyber Samurai Oversized Heavyweight Tee',
    productImage: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=400&q=80',
    category: 'Tops',
    color: 'Black',
    size: 'L',
    location: 'Main Warehouse (WH-01)',
    availableStock: 20,
    reservedStock: 3,
    lowStockThreshold: 5,
    unitCost: 580,
    status: 'In Stock',
    updatedAt: '03 Aug 2026',
    logs: [
      {
        id: 'log-002',
        changeAmount: 20,
        previousStock: 0,
        newStock: 20,
        reason: 'Initial Stock',
        note: 'Factory shipment batch #104',
        user: 'Admin',
        timestamp: '03 Aug 2026, 14:30',
      },
    ],
  },
  {
    id: 'inv-003',
    sku: 'BB-HOD-002-BLK-XL',
    productTitle: 'Neo Tokyo Heavyweight Fleece Hoodie',
    productImage: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=400&q=80',
    category: 'Tops',
    color: 'Black',
    size: 'XL',
    location: 'Fulfillment Center (WH-02)',
    availableStock: 4,
    reservedStock: 1,
    lowStockThreshold: 5,
    unitCost: 1100,
    status: 'Low Stock',
    updatedAt: '02 Aug 2026',
    logs: [
      {
        id: 'log-003',
        changeAmount: 4,
        previousStock: 0,
        newStock: 4,
        reason: 'Initial Stock',
        note: 'Winter hoodie drop batch',
        user: 'Admin',
        timestamp: '02 Aug 2026, 10:15',
      },
    ],
  },
  {
    id: 'inv-004',
    sku: 'BB-KRT-003-WHT-S',
    productTitle: 'Lotus Bloom Hand Painted Linen Kurta',
    productImage: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=400&q=80',
    category: 'Ethnic Wear',
    color: 'White',
    size: 'S',
    location: 'Main Warehouse (WH-01)',
    availableStock: 0,
    reservedStock: 0,
    lowStockThreshold: 3,
    unitCost: 950,
    status: 'Out of Stock',
    updatedAt: '01 Aug 2026',
    logs: [
      {
        id: 'log-004',
        changeAmount: -5,
        previousStock: 5,
        newStock: 0,
        reason: 'Sale',
        note: 'Sold out during festive promo',
        user: 'System',
        timestamp: '01 Aug 2026, 18:45',
      },
    ],
  },
];
