import { ProductType } from './types';

export const INITIAL_PRODUCT_TYPES: ProductType[] = [
  {
    id: 'pt-001',
    name: 'Hoodie',
    slug: 'hoodie',
    shortDescription: 'Heavyweight fleece pullover and zip-up hoodies.',
    fullDescription: 'Premium 380 GSM fleece graphic and plain hoodies designed for winter streetwear, featuring double-lined hoods and reinforced cuffs.',
    parentCategory: 'Tops',
    genderAvailability: ['Men', 'Women', 'Unisex'],
    productsCount: 248,
    featured: true,
    status: 'Active',
    sortOrder: 1,
    priority: 10,
    icon: 'Flame',
    image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=400&q=80',
    color: '#eab308',
    showInNav: true,
    showOnHomepage: true,
    createdDate: '12 Jul 2026',
    defaults: {
      sizeChart: 'Outerwear Fleece (S to 3XL)',
      material: '380 GSM Organic Cotton Fleece',
      taxClass: 'Standard 12%',
      shippingClass: 'Standard Apparel',
    },
    seo: {
      metaTitle: 'Men & Women Hoodies Collection | BatalaBandi',
      metaDescription: 'Shop heavy fleece hoodies and streetwear zip-ups.',
      keywords: 'hoodie, streetwear hoodie, fleece pullover',
    },
    assignedProducts: [
      { id: 'p-101', name: 'Batala Heavyweight Oversized Hoodie', price: '₹2,499', salesCount: 1420, image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=400&q=80', createdDate: '01 Aug 2026' },
      { id: 'p-102', name: 'Vintage Acid Wash Zip Hoodie', price: '₹2,899', salesCount: 890, image: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=400&q=80', createdDate: '28 Jul 2026' },
    ],
  },
  {
    id: 'pt-002',
    name: 'Shirt',
    slug: 'shirt',
    shortDescription: 'Casual, formal, and handcrafted printed shirts.',
    fullDescription: 'Hand-block printed cotton shirts, breathable linen resort shirts, and crisp formal button-downs for all occasions.',
    parentCategory: 'Tops',
    genderAvailability: ['Men', 'Women'],
    productsCount: 185,
    featured: true,
    status: 'Active',
    sortOrder: 2,
    priority: 9,
    icon: 'Shirt',
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=400&q=80',
    color: '#3b82f6',
    showInNav: true,
    showOnHomepage: true,
    createdDate: '10 Jun 2026',
    defaults: {
      sizeChart: 'Shirts Regular Fit (S to XXL)',
      material: '100% Breathable Combed Cotton',
      taxClass: 'Standard 12%',
      shippingClass: 'Standard Apparel',
    },
    seo: {
      metaTitle: 'Handcrafted Printed & Casual Shirts | BatalaBandi',
      metaDescription: 'Unique cotton and linen shirts for men and women.',
      keywords: 'casual shirts, printed shirts, linen shirt',
    },
    assignedProducts: [
      { id: 'p-103', name: 'Kantha Stitch Resort Linen Shirt', price: '₹1,899', salesCount: 1120, image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=400&q=80', createdDate: '25 Jul 2026' },
    ],
  },
  {
    id: 'pt-003',
    name: 'Oversized T-Shirt',
    slug: 'oversized-t-shirt',
    shortDescription: 'Drop-shoulder 240 GSM heavy cotton streetwear tees.',
    fullDescription: 'Ultra-durable 240 GSM drop shoulder t-shirts with high-density screen prints and pre-shrunk fabric finish.',
    parentCategory: 'Tops',
    genderAvailability: ['Men', 'Women', 'Unisex'],
    productsCount: 310,
    featured: true,
    status: 'Active',
    sortOrder: 3,
    priority: 10,
    icon: 'Sparkles',
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=400&q=80',
    color: '#10b981',
    showInNav: true,
    showOnHomepage: true,
    createdDate: '15 May 2026',
    defaults: {
      sizeChart: 'Oversized Boxy Fit',
      material: '240 GSM Super Combed Cotton',
      taxClass: 'Standard 12%',
      shippingClass: 'Standard Apparel',
    },
    seo: {
      metaTitle: '240 GSM Oversized T-Shirts | BatalaBandi',
      metaDescription: 'Heavyweight drop shoulder streetwear graphic tees.',
      keywords: 'oversized tshirt, 240 gsm tee, drop shoulder',
    },
    assignedProducts: [
      { id: 'p-104', name: 'Street Arc Graphic Oversized Tee', price: '₹1,299', salesCount: 3400, image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=400&q=80', createdDate: '02 Aug 2026' },
    ],
  },
  {
    id: 'pt-004',
    name: 'Sweatshirt',
    slug: 'sweatshirt',
    shortDescription: 'Crewneck fleeced thermal sweatshirts.',
    fullDescription: 'Soft interior brush-fleece crewneck sweatshirts engineered for mid-layer insulation and relaxed daily wear.',
    parentCategory: 'Tops',
    genderAvailability: ['Men', 'Women', 'Unisex'],
    productsCount: 92,
    featured: false,
    status: 'Active',
    sortOrder: 4,
    priority: 7,
    icon: 'Layers',
    image: 'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?auto=format&fit=crop&w=400&q=80',
    color: '#6366f1',
    showInNav: true,
    showOnHomepage: false,
    createdDate: '04 Jun 2026',
    defaults: {
      sizeChart: 'Sweatshirt Regular',
      material: '320 GSM Cotton Poly Fleece',
      taxClass: 'Standard 12%',
      shippingClass: 'Standard Apparel',
    },
    seo: {
      metaTitle: 'Crewneck Sweatshirts Collection | BatalaBandi',
      metaDescription: 'Cozy crewneck sweatshirts with minimal branding.',
      keywords: 'sweatshirt, crewneck, fleece top',
    },
  },
  {
    id: 'pt-005',
    name: 'Jacket',
    slug: 'jacket',
    shortDescription: 'Denim, trucker, and bomber outerwear jackets.',
    fullDescription: 'Heavyweight trucker jackets, distressed denim layers, and lined bomber jackets built for longevity.',
    parentCategory: 'Tops',
    genderAvailability: ['Men', 'Women'],
    productsCount: 45,
    featured: true,
    status: 'Active',
    sortOrder: 5,
    priority: 8,
    icon: 'Shield',
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=400&q=80',
    color: '#8b5cf6',
    showInNav: true,
    showOnHomepage: true,
    createdDate: '20 Mar 2026',
    defaults: {
      sizeChart: 'Outerwear Jacket Standard',
      material: 'Heavy Denim Canvas & Fleece Lining',
      taxClass: 'Standard 12%',
      shippingClass: 'Express Courier',
    },
    seo: {
      metaTitle: 'Denim & Bomber Jackets | BatalaBandi',
      metaDescription: 'Durable denim trucker jackets and padded bombers.',
      keywords: 'jackets, denim jacket, bomber jacket',
    },
  },
  {
    id: 'pt-006',
    name: 'Joggers',
    slug: 'joggers',
    shortDescription: 'Relaxed taper cotton sweatpants and joggers.',
    fullDescription: 'Tapered athletic and streetwear joggers with deep zippered pockets and elastic ankle cuffs.',
    parentCategory: 'Bottoms',
    genderAvailability: ['Men', 'Women', 'Unisex'],
    productsCount: 124,
    featured: true,
    status: 'Active',
    sortOrder: 6,
    priority: 8,
    icon: 'Activity',
    image: 'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?auto=format&fit=crop&w=400&q=80',
    color: '#ec4899',
    showInNav: true,
    showOnHomepage: true,
    createdDate: '08 Feb 2026',
    defaults: {
      sizeChart: 'Joggers Waist Sizing (28 to 38)',
      material: '300 GSM French Terry Cotton',
      taxClass: 'Standard 12%',
      shippingClass: 'Standard Apparel',
    },
    seo: {
      metaTitle: 'Men & Women Joggers | BatalaBandi',
      metaDescription: 'Comfortable fleece and French terry joggers.',
      keywords: 'joggers, sweatpants, tapered pants',
    },
  },
  {
    id: 'pt-007',
    name: 'Kurta',
    slug: 'kurta',
    shortDescription: 'Ethnic handcrafted short and long kurtas.',
    fullDescription: 'Hand-painted, kantha-embroidered, and silk blend ethnic kurtas crafted for festive celebrations and modern ethnic wear.',
    parentCategory: 'Ethnic Wear',
    genderAvailability: ['Men', 'Women'],
    productsCount: 68,
    featured: true,
    status: 'Active',
    sortOrder: 7,
    priority: 9,
    icon: 'Sun',
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=400&q=80',
    color: '#f97316',
    showInNav: true,
    showOnHomepage: true,
    createdDate: '14 Jan 2026',
    defaults: {
      sizeChart: 'Ethnic Kurta Standard',
      material: 'Hand-loom Organic Linen & Silk',
      taxClass: 'Reduced 5%',
      shippingClass: 'Standard Apparel',
    },
    seo: {
      metaTitle: 'Handcrafted Ethnic Kurtas | BatalaBandi',
      metaDescription: 'Traditional hand-painted and handloom kurtas.',
      keywords: 'kurta, ethnic wear, kantha kurta',
    },
  },
  {
    id: 'pt-008',
    name: 'Cargo Pants',
    slug: 'cargo-pants',
    shortDescription: 'Multi-pocket tactical & relaxed utility cargos.',
    fullDescription: 'Heavy twill cotton utility cargo pants equipped with 6 tactical flap pockets and adjustable hem drawstrings.',
    parentCategory: 'Bottoms',
    genderAvailability: ['Men', 'Unisex'],
    productsCount: 88,
    featured: false,
    status: 'Active',
    sortOrder: 8,
    priority: 7,
    icon: 'Package',
    image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=400&q=80',
    color: '#14b8a6',
    showInNav: true,
    showOnHomepage: false,
    createdDate: '01 Apr 2026',
    defaults: {
      sizeChart: 'Cargos Relaxed Cut (28 to 38)',
      material: '100% Heavy Cotton Twill',
      taxClass: 'Standard 12%',
      shippingClass: 'Standard Apparel',
    },
    seo: {
      metaTitle: 'Tactical Cargo Pants | BatalaBandi',
      metaDescription: 'Multi-pocket heavy cotton utility cargo pants.',
      keywords: 'cargos, cargo pants, utility pants',
    },
  },
  {
    id: 'pt-009',
    name: 'Tote Bag',
    slug: 'tote-bag',
    shortDescription: 'Heavyweight canvas carryall tote bags.',
    fullDescription: 'Hand-printed 14 oz organic cotton canvas tote bags featuring inner zipper pouches and reinforced cross-stitched handles.',
    parentCategory: 'Accessories',
    genderAvailability: ['Unisex'],
    productsCount: 35,
    featured: false,
    status: 'Active',
    sortOrder: 9,
    priority: 5,
    icon: 'ShoppingBag',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=400&q=80',
    color: '#06b6d4',
    showInNav: false,
    showOnHomepage: false,
    createdDate: '18 Jun 2026',
    defaults: {
      sizeChart: 'One Size Carryall',
      material: '14 oz Organic Canvas',
      taxClass: 'Standard 12%',
      shippingClass: 'Standard Apparel',
    },
    seo: {
      metaTitle: 'Canvas Tote Bags | BatalaBandi',
      metaDescription: 'Durable eco-friendly printed canvas tote bags.',
      keywords: 'tote bag, canvas bag, eco carryall',
    },
  },
  {
    id: 'pt-010',
    name: 'Anarkali Suit',
    slug: 'anarkali-suit',
    shortDescription: 'Festive flare embroidered Anarkali sets.',
    fullDescription: 'Floor-length flared Anarkali silhouettes with fine zari embroidery and matching organza dupattas.',
    parentCategory: 'Ethnic Wear',
    genderAvailability: ['Women'],
    productsCount: 28,
    featured: false,
    status: 'Inactive',
    sortOrder: 10,
    priority: 4,
    icon: 'Sparkle',
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=400&q=80',
    color: '#a855f7',
    showInNav: false,
    showOnHomepage: false,
    createdDate: '05 Jan 2026',
    defaults: {
      sizeChart: 'Women Ethnic Standard',
      material: 'Pure Silk & Organza Dupatta',
      taxClass: 'Reduced 5%',
      shippingClass: 'Express Courier',
    },
    seo: {
      metaTitle: 'Embroidered Anarkali Suits | BatalaBandi',
      metaDescription: 'Festive floor length Anarkalis for special occasions.',
      keywords: 'anarkali suit, zari embroidery, festive wear',
    },
  },
];
