import { ProductItem } from './types';

export const INITIAL_PRODUCTS: ProductItem[] = [
  {
    id: 'prod-001',
    title: 'Cyber Samurai Oversized Heavyweight Tee',
    name: 'Cyber Samurai Oversized Heavyweight Tee',
    subtitle: '240 GSM drop shoulder Japanese cyberpunk street tee',
    slug: 'cyber-samurai-oversized-tee',
    description: 'Premium 240 GSM 100% combed cotton oversized t-shirt featuring high-density screen print artwork of a cyberpunk samurai.',
    sku: 'BB-TSH-001',
    barcode: '890123456789',
    price: 1490,
    compareAtPrice: 1990,
    costPrice: 580,
    stock: 35,
    lowStockThreshold: 5,
    status: 'Active',
    isFeatured: true,
    category: 'Tops',
    productType: 'Oversized T-Shirt',
    collectionName: 'Printed',
    collection: 'Printed',
    themeName: 'Anime',
    theme: 'Anime',
    gender: 'Unisex',
    colors: ['Black', 'White'],
    sizes: ['S', 'M', 'L', 'XL'],
    material: '100% Cotton',
    fitType: 'Oversized',
    images: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=400&q=80',
    variants: [
      { id: 'v-001', sku: 'BB-TSH-001-BLK-M', color: 'Black', colorHex: '#000000', size: 'M', price: 1490, stock: 15 },
      { id: 'v-002', sku: 'BB-TSH-001-BLK-L', color: 'Black', colorHex: '#000000', size: 'L', price: 1490, stock: 20 },
    ],
    seo: {
      metaTitle: 'Cyber Samurai Oversized Heavyweight Tee | BatalaBandi',
      metaDescription: 'Shop 240 GSM anime oversized t-shirts.',
      keywords: 'cyber samurai, anime tee, oversized tshirt',
    },
    salesCount: 890,
    rating: 4.9,
    createdDate: '12 Jan 2026',
    createdAt: '12 Jan 2026',
  },
  {
    id: 'prod-002',
    title: 'Neo Tokyo Heavyweight Fleece Hoodie',
    name: 'Neo Tokyo Heavyweight Fleece Hoodie',
    subtitle: '330 GSM ultra-soft fleece street hoodie',
    slug: 'neo-tokyo-heavyweight-hoodie',
    description: 'Ultra-warm 330 GSM fleece hoodie with double layered hood and kangaroo pocket.',
    sku: 'BB-HOD-002',
    price: 2790,
    compareAtPrice: 3490,
    costPrice: 1100,
    stock: 18,
    lowStockThreshold: 5,
    status: 'Active',
    isFeatured: true,
    category: 'Tops',
    productType: 'Hoodie',
    collectionName: 'Printed',
    collection: 'Printed',
    themeName: 'Anime',
    theme: 'Anime',
    gender: 'Unisex',
    colors: ['Black', 'Navy'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    material: 'Fleece',
    fitType: 'Regular Fit',
    images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=600&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=400&q=80',
    variants: [],
    seo: {
      metaTitle: 'Neo Tokyo Heavyweight Fleece Hoodie | BatalaBandi',
      metaDescription: 'Shop 330 GSM heavy fleece hoodies.',
      keywords: 'hoodie, neo tokyo, anime hoodie',
    },
    salesCount: 1120,
    rating: 4.8,
    createdDate: '15 Feb 2026',
    createdAt: '15 Feb 2026',
  },
  {
    id: 'prod-003',
    title: 'Lotus Bloom Hand Painted Linen Kurta',
    name: 'Lotus Bloom Hand Painted Linen Kurta',
    subtitle: 'Artisan handcrafted pure slub linen kurta',
    slug: 'lotus-bloom-hand-painted-kurta',
    description: 'Hand-painted floral lotus motif on breathable organic slub linen kurta for formal & festive occasions.',
    sku: 'BB-KRT-003',
    price: 2490,
    compareAtPrice: 2990,
    costPrice: 950,
    stock: 12,
    lowStockThreshold: 3,
    status: 'Active',
    isFeatured: true,
    category: 'Ethnic Wear',
    productType: 'Kurta',
    collectionName: 'Hand Painted',
    collection: 'Hand Painted',
    themeName: 'Nature',
    theme: 'Nature',
    gender: 'Women',
    colors: ['White', 'Emerald'],
    sizes: ['S', 'M', 'L'],
    material: 'Linen',
    fitType: 'Regular Fit',
    images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=600&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=400&q=80',
    variants: [],
    seo: {
      metaTitle: 'Lotus Bloom Hand Painted Linen Kurta | BatalaBandi',
      metaDescription: 'Handpainted botanical linen kurta.',
      keywords: 'lotus kurta, hand painted linen',
    },
    salesCount: 520,
    rating: 4.9,
    createdDate: '02 Mar 2026',
    createdAt: '02 Mar 2026',
  },
];

export const MOCK_PRODUCTS = INITIAL_PRODUCTS;
