import { Theme } from './types';

export const INITIAL_THEMES: Theme[] = [
  {
    id: 'theme-001',
    name: 'Anime',
    slug: 'anime',
    shortDescription: 'Japanese manga, cyberpunk & iconic anime art.',
    fullDescription: 'Expressive Japanese manga-inspired illustrations, Tokyo streetwear graphics, and high-density screen prints for anime enthusiasts.',
    productsCount: 248,
    status: 'Active',
    featured: true,
    trending: true,
    showOnHomepage: true,
    homepagePriority: 1,
    showInNav: true,
    createdDate: '12 Jan 2026',
    publishDate: '2026-01-12',
    icon: 'Sparkles',
    bannerImage: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=1200&q=80',
    thumbnailImage: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=400&q=80',
    themeColor: '#ef4444',
    gradientColor: 'from-red-500 to-amber-500',
    compatibleCollections: ['Painted', 'Printed', 'Limited Edition'],
    marketing: {
      tagline: 'Unleash Your Inner Otaku Street Style',
      buttonText: 'Explore Anime Collection',
      buttonUrl: '/themes/anime',
      campaignLabel: 'Trending',
    },
    seo: {
      metaTitle: 'Anime Streetwear & Graphic Apparel | BatalaBandi',
      metaDescription: 'Shop Japanese manga inspired tees, hoodies, and jackets.',
      keywords: 'anime clothing, manga tshirts, otaku streetwear',
    },
    analytics: {
      salesCount: 2410,
      revenue: '₹31,40,000',
      views: 58900,
      conversionRate: '4.2%',
      wishlistCount: 3840,
      averageRating: 4.9,
      monthlySales: [
        { month: 'Mar', amount: 420000 },
        { month: 'Apr', amount: 580000 },
        { month: 'May', amount: 750000 },
        { month: 'Jun', amount: 690000 },
        { month: 'Jul', amount: 700000 },
      ],
    },
    assignedProducts: [
      { id: 'tp-101', name: 'Cyber Samurai Oversized Tee', category: 'Men', productType: 'Oversized T-Shirt', collection: 'Printed', price: '₹1,490', stock: 35, status: 'Active', image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=400&q=80', salesCount: 890 },
      { id: 'tp-102', name: 'Neo Tokyo Heavyweight Hoodie', category: 'Unisex', productType: 'Hoodie', collection: 'Printed', price: '₹2,790', stock: 18, status: 'Active', image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=400&q=80', salesCount: 1120 },
    ],
  },
  {
    id: 'theme-002',
    name: 'Marvel',
    slug: 'marvel',
    shortDescription: 'Superhero & classic comic book graphics.',
    fullDescription: 'Official inspired comic book heritage prints, vintage distressed hero logos, and bold pop art streetwear designs.',
    productsCount: 186,
    status: 'Active',
    featured: true,
    trending: false,
    showOnHomepage: true,
    homepagePriority: 2,
    showInNav: true,
    createdDate: '20 Feb 2026',
    publishDate: '2026-02-20',
    icon: 'Shield',
    bannerImage: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1200&q=80',
    thumbnailImage: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=400&q=80',
    themeColor: '#dc2626',
    gradientColor: 'from-red-600 to-blue-600',
    compatibleCollections: ['Printed', 'Thread', 'Limited Edition'],
    marketing: {
      tagline: 'Assemble Your Hero Wardrobe',
      buttonText: 'Shop Hero Graphics',
      buttonUrl: '/themes/marvel',
      campaignLabel: 'Bestseller',
    },
    seo: {
      metaTitle: 'Comic Book & Superhero Graphic Apparel | BatalaBandi',
      metaDescription: 'Shop hero graphic tees, hoodies, and jackets.',
      keywords: 'marvel clothing, comic book tshirts, hero tees',
    },
    analytics: {
      salesCount: 1980,
      revenue: '₹26,70,000',
      views: 47200,
      conversionRate: '3.9%',
      wishlistCount: 2910,
      averageRating: 4.8,
      monthlySales: [
        { month: 'Mar', amount: 310000 },
        { month: 'Apr', amount: 490000 },
        { month: 'May', amount: 620000 },
        { month: 'Jun', amount: 610000 },
        { month: 'Jul', amount: 640000 },
      ],
    },
    assignedProducts: [
      { id: 'tp-103', name: 'Retro Comic Panel Acid Wash Shirt', category: 'Men', productType: 'Shirt', collection: 'Printed', price: '₹1,990', stock: 24, status: 'Active', image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=400&q=80', salesCount: 640 },
    ],
  },
  {
    id: 'theme-003',
    name: 'Nature',
    slug: 'nature',
    shortDescription: 'Botanical, floral & wildlife hand-painted artwork.',
    fullDescription: 'Tranquil flora & fauna, hand-painted Lotus motifs, and organic botanical dye patterns crafted for earthy aesthetic lovers.',
    productsCount: 142,
    status: 'Active',
    featured: true,
    trending: true,
    showOnHomepage: true,
    homepagePriority: 3,
    showInNav: true,
    createdDate: '05 Mar 2026',
    publishDate: '2026-03-05',
    icon: 'Sun',
    bannerImage: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80',
    thumbnailImage: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=400&q=80',
    themeColor: '#10b981',
    gradientColor: 'from-emerald-500 to-teal-600',
    compatibleCollections: ['Painted', 'Hand Painted', 'Thread'],
    marketing: {
      tagline: 'Earthy Handcrafted Organic Fashion',
      buttonText: 'Discover Nature Art',
      buttonUrl: '/themes/nature',
      campaignLabel: 'Exclusive',
    },
    seo: {
      metaTitle: 'Botanical & Hand Painted Nature Apparel | BatalaBandi',
      metaDescription: 'Shop floral kurtas, botanical shirts, and hand-painted apparel.',
      keywords: 'nature art clothing, botanical shirt, lotus kurta',
    },
    analytics: {
      salesCount: 1450,
      revenue: '₹19,80,000',
      views: 34100,
      conversionRate: '3.8%',
      wishlistCount: 2100,
      averageRating: 4.9,
      monthlySales: [
        { month: 'Mar', amount: 220000 },
        { month: 'Apr', amount: 350000 },
        { month: 'May', amount: 480000 },
        { month: 'Jun', amount: 460000 },
        { month: 'Jul', amount: 470000 },
      ],
    },
    assignedProducts: [
      { id: 'tp-104', name: 'Lotus Bloom Hand Painted Linen Kurta', category: 'Women', productType: 'Kurta', collection: 'Hand Painted', price: '₹2,490', stock: 12, status: 'Active', image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=400&q=80', salesCount: 520 },
    ],
  },
  {
    id: 'theme-004',
    name: 'Quotes',
    slug: 'quotes',
    shortDescription: 'Bold typography, sarcastic & motivational callouts.',
    fullDescription: 'Minimalist typography, vintage newspaper headlines, and witty cultural quotes screen-printed on heavy cotton tees.',
    productsCount: 110,
    status: 'Active',
    featured: false,
    trending: false,
    showOnHomepage: false,
    homepagePriority: 4,
    showInNav: true,
    createdDate: '10 Apr 2026',
    publishDate: '2026-04-10',
    icon: 'MessageSquare',
    bannerImage: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=80',
    thumbnailImage: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=400&q=80',
    themeColor: '#f59e0b',
    gradientColor: 'from-amber-500 to-yellow-400',
    compatibleCollections: ['Printed'],
    marketing: {
      tagline: 'Wear Your Attitude & Thoughts',
      buttonText: 'View Quote Tees',
      buttonUrl: '/themes/quotes',
      campaignLabel: 'Hot',
    },
    seo: {
      metaTitle: 'Typography & Quote Graphic T-Shirts | BatalaBandi',
      metaDescription: 'Witty, sarcastic and motivational quote t-shirts.',
      keywords: 'quote tshirts, typography tees, graphic callout',
    },
    analytics: {
      salesCount: 1120,
      revenue: '₹13,44,000',
      views: 26500,
      conversionRate: '3.6%',
      wishlistCount: 1450,
      averageRating: 4.7,
      monthlySales: [
        { month: 'Mar', amount: 180000 },
        { month: 'Apr', amount: 260000 },
        { month: 'May', amount: 320000 },
        { month: 'Jun', amount: 290000 },
        { month: 'Jul', amount: 294000 },
      ],
    },
    assignedProducts: [],
  },
  {
    id: 'theme-005',
    name: 'Gaming',
    slug: 'gaming',
    shortDescription: 'Esports, 8-bit retro arcade & console aesthetics.',
    fullDescription: 'Pixel art graphics, neon cyberpunk HUD prints, and gaming culture streetwear for esports gamers.',
    productsCount: 95,
    status: 'Active',
    featured: true,
    trending: true,
    showOnHomepage: true,
    homepagePriority: 5,
    showInNav: true,
    createdDate: '18 May 2026',
    publishDate: '2026-05-18',
    icon: 'Gamepad2',
    bannerImage: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80',
    thumbnailImage: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=400&q=80',
    themeColor: '#8b5cf6',
    gradientColor: 'from-purple-600 to-indigo-600',
    compatibleCollections: ['Printed', 'Limited Edition'],
    marketing: {
      tagline: 'Level Up Your Gaming Fit',
      buttonText: 'Explore Gaming Merch',
      buttonUrl: '/themes/gaming',
      campaignLabel: 'New',
    },
    seo: {
      metaTitle: 'Esports & Gaming Streetwear Apparel | BatalaBandi',
      metaDescription: 'Retro 8-bit arcade and esports graphic t-shirts & hoodies.',
      keywords: 'gaming streetwear, esports hoodies, pixel art tees',
    },
    analytics: {
      salesCount: 890,
      revenue: '₹12,40,000',
      views: 22100,
      conversionRate: '3.4%',
      wishlistCount: 1680,
      averageRating: 4.8,
      monthlySales: [
        { month: 'May', amount: 280000 },
        { month: 'Jun', amount: 450000 },
        { month: 'Jul', amount: 510000 },
      ],
    },
    assignedProducts: [],
  },
];
