import { BannerItem, CouponItem } from './types';

export const INITIAL_BANNERS: BannerItem[] = [
  {
    id: 'ban-001',
    title: 'Cyberpunk Anime Drop 2026',
    subtitle: 'Hand-painted oversized heavyweight tees & anime graphic hoodies',
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1200&q=80',
    ctaText: 'Shop New Drop',
    targetLink: '/categories',
    position: 'Hero Carousel',
    sortOrder: 1,
    status: 'Active',
    clicksCount: 340,
  },
  {
    id: 'ban-002',
    title: 'Artisan Hand-Painted Kurta Series',
    subtitle: 'Handcrafted floral lotus & peacock motifs on pure organic slub linen',
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1200&q=80',
    ctaText: 'Explore Ethnic Art',
    targetLink: '/categories',
    position: 'Hero Carousel',
    sortOrder: 2,
    status: 'Active',
    clicksCount: 215,
  },
  {
    id: 'ban-003',
    title: 'Flat 20% OFF Summer Festival Sale',
    subtitle: 'Use code FESTIVE20 on orders above ₹999',
    image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=1200&q=80',
    ctaText: 'Claim Discount',
    targetLink: '/categories',
    position: 'Promo Strip',
    sortOrder: 3,
    status: 'Active',
    clicksCount: 512,
  },
];

export const INITIAL_COUPONS: CouponItem[] = [
  {
    id: 'coup-001',
    code: 'WELCOME20',
    description: '20% Off for first time store shoppers',
    discountType: 'Percentage',
    discountValue: 20,
    minPurchaseAmount: 499,
    maxDiscountAmount: 500,
    usageLimit: 500,
    usedCount: 142,
    status: 'Active',
    expiryDate: '31 Dec 2026',
  },
  {
    id: 'coup-002',
    code: 'FESTIVE500',
    description: 'Flat ₹500 Off on orders above ₹2,499',
    discountType: 'Flat',
    discountValue: 500,
    minPurchaseAmount: 2499,
    usageLimit: 200,
    usedCount: 89,
    status: 'Active',
    expiryDate: '15 Oct 2026',
  },
  {
    id: 'coup-003',
    code: 'FREESHIP',
    description: 'Free Express Air Shipping on all orders',
    discountType: 'Free Shipping',
    discountValue: 0,
    minPurchaseAmount: 0,
    usageLimit: 1000,
    usedCount: 420,
    status: 'Active',
    expiryDate: '31 Dec 2026',
  },
];
